spring:
  application:
    name: database

  datasource:
    # testDB an in-memory H2 Database connecting with jdbc
    url: jdbc:h2:mem:testDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password